version: "3.9"

services:
  db:
    image: postgres:15
    container_name: wispr-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wispr_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: wispr-backend
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASS: secret
      DB_NAME: wispr_dev
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8080:8080"
      - "50051:50051"

volumes:
  db_data:
